### ISSUE TITLE
Request for Raw Data Supporting VetPop Reports

### ISSUE THREAD

**Issue by phillipcarter** [department-of-veterans-affairs/va-data#2]
The VA has published a number of reports in PowerPoint form containing data regarding the veterans population, including:

Education Program Beneficiaries (January 2014) (http://www.va.gov/VETDATA/docs/QuickFacts/Education_Beneficiaries.pdf)

Minority Veterans (May 2013) (http://www.va.gov/vetdata/docs/SpecialReports/Minority_Veterans_2011.pdf)

Profile of Veterans (March 2013) (http://www.va.gov/vetdata/docs/SpecialReports/Profile_of_Veterans_2011.pdf)

However, the raw data supporting these spreadsheets does not appear to be available on the VA data website, nor do these analytical products appear to be derived wholly from the VA VetPop data made available on the website.

Request that the VA publish the raw data supporting these VA policy reports, ideally in spreadsheet or CSV form, so that independent researchers can conduct analysis of these same subjects and the veterans population generally.

**Comment by EmilyTav** [comment]
Great question. I'll look into this and let you know what I find.

**Comment by EmilyTav** [comment]
Phillip, my understanding is that the data used to produce these reports is obtained from Census’ American Community Survey data--that will probably be the quickest and most direct location for the raw files. 

ACS data is available in formats requested at https://www.census.gov/acs/www/data_documentation/data_main/

Another URL that might be helpful:  
Census page explaining survey: https://www.census.gov/acs/www/

Let me know if that helps!

**Comment by paultag** [comment]
Cleaning out issues on this repo, please re-open if that's in error!

**Comment by phillipcarter** [comment]
The VA never responded to this request. I assumed the VA chose not to do so.

**Comment by paultag** [comment]
@phillipcarter this isn't a place to request records, please contact the FOIA officer at the VA and submit a request in writing - this is a place to publish data, not a place to request records!

Hope that helps!

http://www.va.gov/oig/foia/default.asp
