### ISSUE TITLE
FY12 Compensation and Pension by County

### ISSUE THREAD

**Issue by ODVSPatrick** [department-of-veterans-affairs/va-data#4]
When will the Compensation and Pension by county report for FY12 be released (if it hasn't been already).  This is a useful report for us at the state level.

**Comment by EmilyTav** [comment]
Looking into it!

**Comment by ODVSPatrick** [comment]
Have you had a chance to look into this yet?

**Comment by EmilyTav** [comment]
Sorry about the delay on this--a quick follow up (from the team with the answer):  are you referring to the VA Geographical Distribution of Expenditures (GDX) report or something different?

**Comment by ODVSPatrick** [comment]
I was referring to the 2012 version of the report at this link: 

http://catalog.data.gov/dataset/fy2011-compensation-and-pension-by-county 

It has the number of connected veterans in each county and the rate they are connected at.

**Comment by EmilyTav** [comment]
Great, thank you Patrick. They should be getting me an answer shortly.

**Comment by ODVSPatrick** [comment]
Thanks.

**Comment by ODVSPatrick** [comment]
Did you hear anything yet?

**Comment by ODVSPatrick** [comment]
Any updates yet?

**Comment by EmilyTav** [comment]
Patrick, the office has alerted me that this should be posted in the next 10 days. I will shoot you the link as soon as it's up. Thanks for your patience!

**Comment by ODVSPatrick** [comment]
Thanks!  These files are very useful.

**Comment by ODVSPatrick** [comment]
Have you heard from the office yet?

**Comment by ODVSPatrick** [comment]
I found the files on http://www.va.gov/vetdata/.  Thanks.

**Comment by EmilyTav** [comment]
Patrick, really sorry I couldn't help more on this.

**Comment by ODVSPatrick** [comment]
That's ok.  They were just up today and I hadn't seen them on that site before.

**Comment by EmilyTav** [comment]
If you're up for it, I'd love to connect and hear more about the work you are doing. If you're interested, email me and lets set some time up for a call sometime in the next few weeks: emily.tavoulareas@va.gov

**Comment by EmilyTav** [comment]
@ODVSPatrick: any chance you have a few moments to give us some feedback on VA data and your needs? Your feedback will help us prioritize future data releases! 

https://docs.google.com/forms/d/1NjUc0Ne7k1tkZevfXM5BmbPJ6op2Qs1z7TDo2MIRA1Q/viewform

Your feedback is much appreciated, keep it comin!

**Comment by ODVSPatrick** [comment]
I would be happy to give feedback.  I looked at this survey and I don't think it applies to us. We are not creating any data ourselves; we are using the VA's data.

**Comment by paultag** [comment]
Cleaning out issues on this repo, please re-open if that's in error!
