### ISSUE TITLE
"Clone in Desktop" does not launch on my machine- Help!!

### ISSUE THREAD

**Issue by wango123** [department-of-veterans-affairs/va-data#7]
I want to upload files to my subdirectory named: "department-of-veterans-affairs/VA_OPEN_DATA_IPT". I am going about it by lauching the "Clone in Desktop" app that is native to GitHub. I just does not launch. Any ideas?

The alternative is to use an app that I found on the internet: How To Deploy File To Github From Windows. I cant use that app on some machines for security/administative reasons.

**Comment by jalbertbowden** [comment]
cmd is the default, it never fails

**Comment by wango123** [comment]
Thanks a bunch. Let me try to figure out what that command is unless you have it handy.

**Comment by jalbertbowden** [comment]
lol....ok then....just so we are clear, your local repo is ahead of master? and you want to sync them, correct?

**Comment by wango123** [comment]
No it is

https://github.com/department-of-veterans-affairs/VA_OPEN_DATA_IPT.

Actually it looks like in the caption below.

Thanks,

Michael Miti-Kavuma

[cid:image001.png@01CF65F5.0A5B9240]

**Comment by wango123** [comment]
I was able to upload those files using some app on the internet and not the app that is native to GitHub.

**Comment by jalbertbowden** [comment]
ok...so you're good?

**Comment by wango123** [comment]
No. I  don’t know what the cmd prompt is and where to put it. I am very new to all this.  Just walk me through it and I will fiddle with the rest.

Thanks,

Michael Miti-Kavuma
ASD

**Comment by jalbertbowden** [comment]
hmm....ok. well now i'm really confused. but here goes:  
to use git, in windows its cmd, os x/linux its terminal, but they're essentially the same in context. you are going to want to cd into the repo that you want to sync, and then type git status and hit enter. git status will tell you the status of the repo that you are in....if you have new/updated files, for each type git add filename and hit enter. once you are done adding them, type git commit -m "commit explanationn"  
after git commit runs, then git push origin master and hit enter  
this will push your repo to its origin master, which is hosted on github.  
if you don't already have your password saved for later use, you're going to have to authenticate your github account to push; you'll see the prompt in cmd to enter your account credentials.  
i hope that makes sense...

**Comment by blacktm** [comment]
You guys might want to check out these resources:
- https://guides.github.com
- https://training.github.com/kit/downloads/github-git-cheat-sheet.pdf
- https://try.github.io/

**Comment by wango123** [comment]
Thanks for you tips.

My problem, I have just figured out is I did not have git installed on my machine. Let me get admin rights to it, install it (git) and then take it from there.

Git –version    gives me “git’ is not recognized as an internal or external command, operable program or bath file.

Wango123

**Comment by blacktm** [comment]
When you get admin rights, downloading the GitHub app (https://windows.github.com) is by far the easiest way to get started – it will automate all the setup stuff, like installing and configuring Git.

**Comment by paultag** [comment]
Cleaning out issues on this repo, please re-open if that's in error!
