### ISSUE TITLE
SORN data lised in the json (and therefore data.gov) doesn't link to the correct file

### ISSUE THREAD

**Issue by ErieMeyer** [department-of-veterans-affairs/va-data#9]
Hi!

The data json currently links to the wrong place on va.gov for SORNs.

This should replace the current link to sorns: http://www.oprm.va.gov/privacy/systems_of_records.aspx

Here's where the wrong location is posted on data.gov: http://catalog.data.gov/dataset/va-system-of-records-notices-sorns

cc @rebeccawilliams

**Comment by paultag** [comment]
Going through some old issues, is there still work on this ticket?

**Comment by wango123** [comment]
The correct URL was entered in the www.inventory.data.gov for this dataset. This was done on November 25, 2015.

**Comment by wango123** [comment]
Thanks a lot Paul.

Michael Miti-Kavuma, PMP
IT Specialist
VA OI&T Open Data Group (VOODG)
Office of Technology Strategies (TS)
Office of Architecture, Strategy, and Design (ASD)
Office of Information & Technology (OI&T)
Department of Veterans Affairs
801 I St. NW, Suite 1250B
Washington DC 20001
PH: 202-461-4394 (Office)
PH: 202-957-2352 (B/B)
PH. 240-330-0161 (Cell) - Preferred
